---
deployment:
  tasks:
    - export DEPLOYPATH=/home/centafol/public_html
    - /usr/local/bin/npm install
    - /usr/local/bin/npm run build
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R dist/* $DEPLOYPATH
